# Generated by Django 4.2.5 on 2023-09-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0002_remove_coachmodel_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachmodel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='coachs/'),
        ),
        migrations.AlterModelTable(
            name='coachmodel',
            table='coach',
        ),
    ]
