# Generated by Django 4.2.5 on 2023-09-09 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coach', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.URLField(blank=True, default='', null=True)),
                ('phote', models.ImageField(blank=True, null=True, upload_to='gyms/')),
                ('phone', models.CharField(max_length=13)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coach.coachmodel')),
            ],
        ),
    ]
