# Generated by Django 4.2.5 on 2023-09-09 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gymmodel',
            table='GYM',
        ),
    ]
